#!/bin/zsh
DOTFILEDIR="$HOME/dotfiles"

echo "Checking for updates..."
({cd $DOTFILEDIR && git fetch -q} &> /dev/null)
 
if [ $({cd $DOTFILEDIR} &> /dev/null && git rev-list HEAD...origin/master | wc -l) = 0 ]
then
	echo "Already up to date."
else
	echo "Updates Detected:"
	({cd $DOTFILEDIR} &> /dev/null && git log ..@{u} --pretty=format:%Cred%aN:%Creset\ %s\ %Cgreen%cd)
	echo "Setting up..."
	({cd $DOTFILEDIR} &> /dev/null && git pull -q && git submodule update --init --recursive)
fi

source $DOTFILEDIR/zsh/.config/zsh/zshrc.sh
