#!/usr/bin/env bash

declare -i KEY
KEY=`xinput list | grep -Eio 'Caldigit, Inc.*.id\=[0-9]{1,2}' | grep -Eo '[0-9]{2}'`
declare -i STATE
STATE=`xinput list-props $KEY | grep 'Device Enabled' | awk '{print $4}'`

if [[ $STATE -eq 1 ]]; then
    echo "Docking laptop"
    # sets monitor stuff up for main monitor
    bash ~/dotfiles/i3/scripts/main_with_dock.sh
    sleep 0.5
    # launches polybar config to get bar for every monitor
    bash ~/dotfiles/polybar/launch.sh &
    sleep 0.5
    i3-msg restart
else
    echo "Undocking laptop"
    bash ~/dotfiles/i3/scripts/main_without_dock.sh
    sleep 0.5
    # relaunches polybar config
    bash ~/dotfiles/polybar/launch.sh &
    sleep 0.5
    i3-msg restart
fi
