#!/usr/bin/env bash

# sleep 5

declare -i KEY
KEY=`xinput list | grep -Eio 'Caldigit, Inc.*.id\=[0-9]{1,2}' | grep -Eo '[0-9]{2}'`
declare -i STATE
STATE=`xinput list-props $KEY | grep 'Device Enabled' | awk '{print $4}'`

MONITOR=$1

if [[ $STATE -eq 1 ]]; then
    if [[ $MONITOR = "--portrait" ]]; then
        echo "Docking laptop Portrait"
        # sets monitor stuff up for main monitor
        bash ~/dotfiles/scripts/main_dock.sh
        sleep 0.2
        sleep 0.2
    else
        echo "Docking laptop - normal"
        # sets monitor stuff up for main monitor
        bash ~/dotfiles/scripts/docked_non_portrait.sh
        sleep 0.2
        sleep 0.2
    fi
else
        echo "Undocking laptop"
        bash ~/dotfiles/scripts/main_no_dock.sh
        sleep 0.2
        sleep 0.2
fi
