#!/bin/bash

if docker ps | grep -q kali-linux; then
    docker-compose -f $HOME/development/kali-docker/docker-compose.yml down
else
    docker-compose -f $HOME/development/kali-docker/docker-compose.yml up -d
    sleep 0.1
    ssh 10.1.0.2
fi
