#!/bin/bash

USER=mdube
WIDTH=1920
HEIGHT=1080
KALIDIR="$HOME/development/kali-docker"

container_status() {
    # Check if container is online
    if [ "$(docker ps | grep "kali-linux" | awk '{ print $2 }')" = "kali-linux" ]; then
        return 1 || return 0
    fi
}

case "$1" in
    stop|drop)
    container_status
    if [ $? -eq 1 ]; then
        docker-compose -f $KALIDIR/docker-compose.yml down
    else
        echo "kali-docker is not running"
    fi
    echo "exit code $?"
    ;;

    attach)
    container_status
    if [ $? -eq 1 ]; then
        docker exec -ti kali-linux /bin/zsh
    else
        docker-compose -f $KALIDIR/docker-compose.yml up -d 
        docker exec -ti kali-linux /bin/zsh
    fi
    ;;

    rdp)
    container_status
    if [ $? -eq 1 ]; then
        xfreerdp /u:$USER /p: /v:10.1.0.2 /w:$WIDTH /h:$HEIGHT
    else
        docker-compose -f $KALIDIR/docker-compose.yml up -d 
        xfreerdp /u:$USER /p: /v:10.1.0.2 /w:$WIDTH /h:$HEIGHT
    fi
    ;;

    rdp-full)
    container_status
    if [ $? -eq 1 ]; then
        xfreerdp /u:$USER /p: /v:10.1.0.2 /w:3440 /h:1440
    else
        docker-compose -f $KALIDIR/docker-compose.yml up -d 
        xfreerdp /u:$USER /p: /v:10.1.0.2 /w:3440 /h:1440
    fi
    ;;

    update)
    """
    If XRDP is running when the image is updated with docker commit, it will break RDP.
    Because of the way docker works, this would mean XRDP would need to be restarted everytime you start the container.

    If you update the container with this script, it will turn off xrdp beforehand, which fixes this issue.
    """
    container_status
    if [ $? -eq 1 ]; then
        # stop xrdp
        echo "Killing XRDP..."
        docker exec -ti kali-linux service xrdp stop
        # Update the image
        echo "Updating kali-linux image"
        docker commit kali-linux kali-linux
    else
        echo "Container is not running, image cannot be updated"
    fi
    ;;
    restart)
    docker-compose -f $KALIDIR/docker-compose.yml restart
    ;;
    -h|help)
    echo "Available arguments: attach, stop, rdp, update, restart"
    ;;
    *)
    echo "Container Status:"
    container_status
    if [ $? -eq 1 ]; then
        echo "Kali docker container online"
    else
        echo "Kali docker container offline"
    fi
    ;;
esac
