#!/bin/bash

timestamp=$(date +%F)

cp "$HOME/notes/💡resources/Templates/Main Note Template.md" ".tempNote.md"

# Opens neovim and calls the function CreateNotes
# CreateNotes opens the .tempNote.md file, and sets the filetype to vimwiki
nvim -c "call CreateNotes()"

# Grabs the title given from the note template to use in the new filename
notetitle=$(grep -o "Note:.*" .tempNote.md | cut -f2- -d:)

# Concatanates the note title with the full date
filename="${notetitle} ${timestamp}"

mv ".tempNote.md" "$HOME/notes/🧹 Areas/📭 Thoughts/$filename.md"
