#!/bin/bash

setup(){
    echo "Setup Penetration Test"

    printf "\n"
    read -p "[+] IPT or EPT: " PTtype
    printf "\n"

    read -p "[+] Client name: " PTclient
    PTclient=$(sed 's/ /_/g' <<< "$PTclient")
    read -p "[+] Service: " PTservice

    PTname="${PTtype}_${PTclient}_${PTservice}"
    echo $PTname

    # Create folder for PT
    mkdir -p $HOME/clients/"$PTname"

    if [ "$PTtype" = "IPT" ] || [ "$PTtype" = "ipt" ]; then
        IPT
    else 
        exit
        # Restart zsh to have the env var of $IP without having a nested session
        exec zsh
    fi 
}

IPT(){
    # Get IP address and append it into readme
    read -p "RNA IP: " RNAIP

    # Replace $IP with proper RNA IP
    sed -i '/IP=/s/".*"/"'$RNAIP'"/' $HOME/.config/zsh/exports.zsh

    echo -e "[+] IP Address for $PTname: ${red}$RNAIP"
    # Restart zsh to have the env var of $IP without having a nested session
    exec zsh
}

setup
