#!/bin/bash

if [ -z $1 ];then
    printf "\n"
    read -p "Please enter name of CTF: " CTFname
    printf "\n"
else
    CTFname=$1
fi

echo "CTF: $CTFname"

# Create folders for CTF if they don't already exist - useful if restarting CTF from earlier
if [ ! -d "$HOME/CTF/$CTFname" ];then
    mkdir $HOME/CTF/"$CTFname"
    mkdir $HOME/CTF/"$CTFname/nmap"
    mkdir $HOME/CTF/"$CTFname/users"
    mkdir $HOME/CTF/"$CTFname/passwords"
fi

# Create readme file
touch $HOME/CTF/"$CTFname/README.md"
echo "# $CTFname" >> "$HOME/CTF/$CTFname/README.md"

# Get IP address and append it into readme
read -p "IP Address: " IPaddr
echo -e "\n#### IP Address" >> "$HOME/CTF/$CTFname/README.md"
echo -e "\n"'```bash\n'EXPORT IP=$IPaddr'\n```' >> "$HOME/CTF/$CTFname/README.md"


# Replace $IP with proper IP address given
sed -i '/IP=/s/".*"/"'$IPaddr'"/' $HOME/dotfiles/zsh/conf/exports.zsh

# Restart zsh to have the env var of $IP without having a nested session
exec zsh

# Starting on setting up Tmux panels
# Only create tmux session if it doesn't already exist
if [ "$SESSIONEXISTS" = "" ]
then
    # Start New Session with our name
    tmux new-session -d -s $SESSION

    # Name first Pane and start zsh
    tmux rename-window -t 1 'OpenVPN'
    tmux send-keys -t 'OpenVPN' C-m

    # setup Main window
    tmux new-window -t $SESSION:2 -n 'Main'
    tmux send-keys -t 'Main' "lvim" C-m

    # setup other  window
    tmux new-window -t $SESSION:3 -n 'Misc'
    # tmux send-keys -t 'Neovim' "nvim" C-m
fi

# Attach Session, on the Main window
tmux attach-session -t $SESSION:1

echo $IP
