#!/bin/bash

printf "\n"
read -p "Please enter name of CTF: " CTFname
printf "\n"

echo "CTF: $CTFname"

# Create folders for CTF
mkdir $HOME/CTF/"$CTFname"
mkdir $HOME/CTF/"$CTFname/nmap"
mkdir $HOME/CTF/"$CTFname/users"
mkdir $HOME/CTF/"$CTFname/passwords"

# Create readme file
touch $HOME/CTF/"$CTFname/README.md"
echo "# $CTFname" >> "$HOME/CTF/$CTFname/README.md"

# Get IP address and append it into readme
read -p "IP Address: " IPaddr
echo -e "\n#### IP Address" >> "$HOME/CTF/$CTFname/README.md"
echo -e "\n"'```bash\n'EXPORT IP=$IPaddr'\n```' >> "$HOME/CTF/$CTFname/README.md"


# Replace $IP with proper IP address given
sed -i '/IP=/s/".*"/"'$IPaddr'"/' $HOME/dotfiles/zsh/conf/exports.zsh

# Restart zsh to have the env var of $IP without having a nested session
exec zsh
