#!/bin/bash

FILENAME=${1?Specifiy a filename, Dumbass}
COUNTER=1

if [ -z "$TMUX" ]; then
  echo "open tmux, dumbass"
  exit 1
fi

if [[ -n "$TMUX_PANE" ]]; then
  session_name=$(tmux list-panes -t "$TMUX_PANE" -F '#S' | head -n1)
fi

for l in $(cat $FILENAME); do
  COUNTER=$[COUNTER + 1]
  tmux new-window -t $session_name:$COUNTER -n $l
  tmux send-keys "export IP=$l" C-m
  tmux send-keys "customAutomator -H $l -t All" C-m
done
