#!/bin/bash

# Set Session Name
SESSION="Main"
SESSIONEXISTS=$(tmux list-sessions | grep $SESSION)

# Only create tmux session if it doesn't already exist
if [ "$SESSIONEXISTS" = "" ]
then
    # Start New Session with our name
    tmux new-session -d -s $SESSION

    # Name first Pane and start zsh
    tmux rename-window -t 1 'Terminal'
    tmux send-keys -t 'Terminal' C-m

    # setup Neovim window
    tmux new-window -t $SESSION:2 -n 'Neovim'
    tmux send-keys -t 'Neovim' "nvim" C-m

    # setup other  window
    tmux new-window -t $SESSION:3 -n 'Other'
    # tmux send-keys -t 'Neovim' "nvim" C-m

    # setup ssh window
    tmux new-window -t $SESSION:4 -n 'SSH'

    # Setup an additional shell
    tmux new-window -t $SESSION:5 -n 'Dotfiles'
    tmux send-keys -t 'Dotfiles' "cd ~/dotfiles" C-m "clear" C-m
fi

# Attach Session, on the Main window
tmux attach-session -t $SESSION:1
