#!/bin/bash

declare -i VOLUME
VOLUME=`amixer | grep 'Front Left: Playback' | awk '{print $5}' | sed 's/%//' | sed 's/\[//' | sed 's/]//'`

echo $VOLUME

if [[ $VOLUME -eq 100 ]]; then
    amixer -D pulse sset Master 0%
elif [[ $VOLUME -eq 0 ]]; then
    amixer -D pulse sset Master 100%
fi
