#!/bin/sh
xrandr --output eDP-1 --primary --mode 1920x1080 --rate 144 --pos 1284x154 --rotate normal --output DP-1-0 --off --output DP-1-1 --off --output DP-1-2 --off --output DP-1-3 --off --output HDMI-1-0 --off --output DP-1-4 --off
sleep 1
# relaunches polybar config
bash ~/dotfiles/polybar/launch.sh &
